### ISSUE TITLE
Unknown type: TokenLib.ModuleData storage

### ISSUE THREAD

**Issue by shuffledex** [ethereum-ts/TypeChain#125]
Trying to compile this part of json:

```
    {
      "constant": false,
      "inputs": [
        {
          "name": "_moduleData",
          "type": "TokenLib.ModuleData storage"
        },
        {
          "name": "_module",
          "type": "address"
        }
      ],
      "name": "archiveModule",
      "outputs": [],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function"
    }
```

I'm getting `Unknown type: TokenLib.ModuleData storage` and the execution stoped.

**Comment by krzkaczor** [comment]
@shuffledex Frankly, I have no idea what `TokenLib.ModuleData storage`is. Do you have source code of the smart contract that generated such ABI?

**Comment by stwiname** [comment]
It will be referring to a [Library](https://solidity.readthedocs.io/en/latest/contracts.html#libraries)

Example in link includes `Data storage data`

**Comment by quezak** [comment]
@shuffledex can you provide a full minimal example contract and library that generate the json you posted? I'll probably soon be working on linking contracts with (non-external) libraries, so I may take a look at your case too.

**Comment by krzkaczor** [comment]
This should be fixed in `typechain@1.0.2`, if not please reopen and provide repro ;)

**Comment by stwiname** [comment]
I'm still facing this issue after updating to `typechain@1.0.3`. I've attached a zip of the JSON files generated from `truffle@5.0.32` compiler.

Let me know if I can be more help. I can create a more complete example if necessary.

[Archive.zip](https://github.com/ethereum-ts/TypeChain/files/3766439/Archive.zip)

**Comment by quezak** [comment]
OK, leaving this issue closed, continuing in #216
